# 1. Load important libraries

In [2]:
"""
1. Load important libraries
"""
try:
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    print("imported successfully")

except ImportError as error:
    print(str(error))

imported successfully

# 2. Load the dataset carefully

In [3]:
# DATASET -> New York City AirBnB data
df = pd.read_csv(r"C:\Users\Arijit\Downloads\archive\Airbnb_Open_Data.csv", low_memory=False)
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

# 3. Explore the dataset

In [4]:
print("Total rows : ", df.shape[0])
print("Total columns : ", df.shape[1])
print("Data dimension : ", df.ndim, "\n")
print("Data type : \n", df.dtypes)
print(type(df))

Total rows :  102599
Total columns :  26
Data dimension :  2

Data type :
 id                                  int64
NAME                               object
host id                             int64
host_identity_verified             object
host name                          object
neighbourhood group                object
neighbourhood                      object
lat                               float64
long                              float64
country                            object
country code                       object
instant_bookable                   object
cancellation_policy                object
room type                          object
Construction year                 float64
price                              object
service fee                        object
minimum nights                    float64
number of reviews                 float64
last review                        object
reviews per month                 float64
review rate number                float64
calculated host listings count    float64
availability 365                  float64
house_rules                        object
license                            object
dtype: object
<class 'pandas.core.frame.DataFrame'>

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

# 4. Columns transformation

In [6]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [7]:
# Drop columns which is not important
columns_to_drop = ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'country code', 'last review']

df.drop(columns=columns_to_drop, inplace=True)
print("Total columns now : ", df.shape[1])

Total columns now :  18

In [8]:
print("Total columns : ", df.shape[1])

Total columns :  18

In [9]:
# Replacing special characters
special_chars = "!@#$%^&*()+-=[]{}|;':\",./<>?`~\\"

for chars in special_chars:
    df.columns = df.columns.str.replace(
        chars, ""
    )

# Updating columns letter cases
df.columns = df.columns.str.lower()
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ", "_")
df.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews'],
      dtype='object')

In [10]:
df

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,True,flexible,Private room,2005.0,$620,$124,3.0,0.0
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,False,flexible,Private room,2003.0,$844,$169,1.0,0.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,True,moderate,Private room,2016.0,$837,$167,1.0,1.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,True,moderate,Private room,2009.0,$988,$198,3.0,0.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0

# 5 Handling Duplicates

In [11]:
# Exploring duplicates
"""
- We have to drop duplicates based on our goal.
- If duplicates rows gives meaningful insights then we dont have to drop those rows.
- Otherwise it will give us wrong insights.

"""

print("Total rows : ", df.shape[0])
print("Total duplicate rows : ", df.duplicated().sum())
print("Total unique rows : ", len(df)-df.duplicated().sum())
print("Duplicate percentage : ", np.trunc((df.duplicated().sum()/len(df))*100), "%")

Total rows :  102599
Total duplicate rows :  541
Total unique rows :  102058
Duplicate percentage :  0.0 %

# 6. Handle Missing Values (NaN)

In [12]:
print("Total null values : \n", df.isnull().sum(), "\n")
print("Null percentage/column : ")
(df.isnull().sum()/len(df))*100

Total null values :
 id                          0
name                      250
host_id                     0
host_identity_verified    289
host_name                 406
neighbourhood_group        29
neighbourhood              16
lat                         8
long                        8
country                   532
instant_bookable          105
cancellation_policy        76
room_type                   0
construction_year         214
price                     247
service_fee               273
minimum_nights            409
number_of_reviews         183
dtype: int64

Null percentage/column :

id                        0.000000
name                      0.243667
host_id                   0.000000
host_identity_verified    0.281679
host_name                 0.395715
neighbourhood_group       0.028265
neighbourhood             0.015595
lat                       0.007797
long                      0.007797
country                   0.518524
instant_bookable          0.102340
cancellation_policy       0.074075
room_type                 0.000000
construction_year         0.208579
price                     0.240743
service_fee               0.266084
minimum_nights            0.398639
number_of_reviews         0.178364
dtype: float64

In [13]:
# Getting the int and float type columns

for column in df.columns:
    if df[column].dtype == "int64" or df[column].dtype == "float64":
        print(column, "=",df[column].dtype, "=",df[column].isnull().sum())

id = int64 = 0
host_id = int64 = 0
lat = float64 = 8
long = float64 = 8
construction_year = float64 = 214
minimum_nights = float64 = 409
number_of_reviews = float64 = 183

In [14]:
# Column => df["lat"]

print("Mean : ",np.trunc(df["lat"].mean()))
print("Median : ", np.trunc(df["lat"].median()))

difference = df["lat"].mean() - df["lat"].median()
print("Differnce : ", np.trunc(difference))

df["lat"] = df["lat"].replace(np.nan, df["lat"].mean())
df["lat"].isnull().sum()

Mean :  40.0
Median :  40.0
Differnce :  0.0

np.int64(0)

In [15]:
# Column => df["long"]

print("Mean : ",np.trunc(df["long"].mean()))
print("Median : ", np.trunc(df["long"].median()))

difference = df["long"].mean() - df["long"].median()
print("Differnce : ", np.trunc(difference))


df["long"] = df["long"].replace(np.nan, df["long"].mean())
df["long"].isnull().sum()

Mean :  -73.0
Median :  -73.0
Differnce :  0.0

np.int64(0)

In [16]:
# Column => df["construction_year"]
print("Mean : ",np.trunc(df["construction_year"].mean()))
print("Median : ", np.trunc(df["construction_year"].median()))

difference = df["construction_year"].mean() - df["construction_year"].median()
print("Differnce : ", np.trunc(difference))

df["construction_year"] = df["construction_year"].replace(np.nan, df["construction_year"].mean())
df["construction_year"].isnull().sum()

Mean :  2012.0
Median :  2012.0
Differnce :  0.0

np.int64(0)

In [17]:
# Column => df["minimum_nights"]
print("Mean : ",np.trunc(df["minimum_nights"].mean()))
print("Median : ", np.trunc(df["minimum_nights"].median()))

difference = df["minimum_nights"].mean() - df["minimum_nights"].median()
print("Differnce : ", np.trunc(difference))

df["minimum_nights"] = df["minimum_nights"].replace(np.nan, df["minimum_nights"].median())
df["minimum_nights"].isnull().sum()

Mean :  8.0
Median :  3.0
Differnce :  5.0

np.int64(0)

In [18]:
# Column = df["number_of_reviews"]

print("Mean : ",np.trunc(df["number_of_reviews"].mean()))
print("Median : ", np.trunc(df["number_of_reviews"].median()))

difference = df["number_of_reviews"].mean() - df["number_of_reviews"].median()
print("Differnce : ", np.trunc(difference))

print("Maximum value : ", df["number_of_reviews"].max())
print("Minimum value : ", df["number_of_reviews"].min())

df["number_of_reviews"] = df["number_of_reviews"].replace(np.nan, df["number_of_reviews"].median())
df["number_of_reviews"].isnull().sum()

Mean :  27.0
Median :  7.0
Differnce :  20.0
Maximum value :  1024.0
Minimum value :  0.0

np.int64(0)

In [19]:
# printing catagorical column
for column in df.columns:
    if df[column].dtype == "object":
        if df[column].isnull().sum()>0:
            missing_pct = np.trunc((df[column].isnull().sum()/len(df[column]))*100)
            if missing_pct <= 10:
                df[column] = df[column].replace(np.nan, df[column].mode()[0])

C:\Users\Arijit\AppData\Local\Temp\ipykernel_5196\1720665480.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column] = df[column].replace(np.nan, df[column].mode()[0])

In [20]:
print("Total null values now : \n", df.isnull().sum())

Total null values now :
 id                        0
name                      0
host_id                   0
host_identity_verified    0
host_name                 0
neighbourhood_group       0
neighbourhood             0
lat                       0
long                      0
country                   0
instant_bookable          0
cancellation_policy       0
room_type                 0
construction_year         0
price                     0
service_fee               0
minimum_nights            0
number_of_reviews         0
dtype: int64

# 7 Cleaning Individual Columns

In [21]:
df

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,unconfirmed,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,True,flexible,Private room,2005.0,$620,$124,3.0,0.0
3,1002755,Home away from home,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,False,flexible,Private room,2003.0,$844,$169,1.0,0.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,True,moderate,Private room,2016.0,$837,$167,1.0,1.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,True,moderate,Private room,2009.0,$988,$198,3.0,0.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0

In [22]:
# correcting object type columns
# generic cleaning
for column in df.columns:
    if df[column].dtype == "object":
        df[column] = df[column].str.lower() # converting it into lowercase letters
        df[column] = df[column].str.strip() # removing extra spaces
        df[column] = df[column].str.replace("\n", "")

In [23]:
df

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,1001254,clean & quiet apt home by the park,80014485718,unconfirmed,madaline,brooklyn,kensington,40.64749,-73.97237,united states,False,strict,private room,2020.0,$966,$193,10.0,9.0
1,1002102,skylit midtown castle,52335172823,verified,jenna,manhattan,midtown,40.75362,-73.98377,united states,False,moderate,entire home/apt,2007.0,$142,$28,30.0,45.0
2,1002403,the village of harlem....new york !,78829239556,unconfirmed,elise,manhattan,harlem,40.80902,-73.94190,united states,True,flexible,private room,2005.0,$620,$124,3.0,0.0
3,1002755,home away from home,85098326012,unconfirmed,garry,brooklyn,clinton hill,40.68514,-73.95976,united states,True,moderate,entire home/apt,2005.0,$368,$74,30.0,270.0
4,1003689,entire apt: spacious studio/loft by central park,92037596077,verified,lyndon,manhattan,east harlem,40.79851,-73.94399,united states,False,moderate,entire home/apt,2009.0,$204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,spare room in williamsburg,12312296767,verified,krik,brooklyn,williamsburg,40.70862,-73.94651,united states,False,flexible,private room,2003.0,$844,$169,1.0,0.0
102595,6092990,best location near columbia u,77864383453,unconfirmed,mifan,manhattan,morningside heights,40.80460,-73.96545,united states,True,moderate,private room,2016.0,$837,$167,1.0,1.0
102596,6093542,"comfy, bright room in brooklyn",69050334417,unconfirmed,megan,brooklyn,park slope,40.67505,-73.98045,united states,True,moderate,private room,2009.0,$988,$198,3.0,0.0
102597,6094094,big studio-one stop from midtown,11160591270,unconfirmed,christopher,queens,long island city,40.74989,-73.93777,united states,True,strict,entire home/apt,2015.0,$546,$109,2.0,5.0
102598,6094647,585 sf luxury studio,68170633372,unconfirmed,rebecca,manhattan,upper west side,40.76807,-73.98342,united states,False,flexible,entire home/apt,2010.0,"$1,032",$206,1.0,0.0

In [24]:
# specific cleaning
df.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews'],
      dtype='object')

In [25]:
# cleaning columns which is numeric but contains special characters.
df[['price', 'service_fee']].dtypes

price          object
service_fee    object
dtype: object

In [ ]:
columns = ['price', 'service_fee']

for column in columns:
    df[column] = df[column].str.replace(r'[^0-9]', '', regex=True) # removes special characters
    df[column] = df[column].astype(int)
    
df[['price', 'service_fee']]
print(df[columns].dtypes)

price          int64
service_fee    int64
dtype: object

In [27]:
for column in df.columns:
    if df[column].dtype == "object":
        print(column)

name
host_identity_verified
host_name
neighbourhood_group
neighbourhood
country
cancellation_policy
room_type

In [28]:
# columns => name

df['name']

0                       clean & quiet apt home by the park
1                                    skylit midtown castle
2                      the village of harlem....new york !
3                                      home away from home
4         entire apt: spacious studio/loft by central park
                                ...
102594                          spare room in williamsburg
102595                       best location near columbia u
102596                      comfy, bright room in brooklyn
102597                    big studio-one stop from midtown
102598                                585 sf luxury studio
Name: name, Length: 102599, dtype: object

In [29]:
df['name'].value_counts().sample(10)

name
one bedroom in luxury fidi building                   3
cheerful 3-bedroom villa w/ parking & patio           1
travelers private room                                3
stylish parkside midcentury apt                       4
amazing room in heart of east village                 1
✨cute & cozy west village studio✨                     1
stylish 1 br loft apt williamsburg                    1
private bedroom private bathroom in brooklyn, ny      1
private, cozy room, 20 min to manhattan               2
private room,1 min from subway,20 min to manhattan    2
Name: count, dtype: int64

In [30]:
# checking if same id contains different name.
"""
if same id contains different name then it's wrong. because same id can not contain different name like,

id      name
1       John
1       Charlie

here id=1 contains different name, it's a mistake.
"""
df.groupby('id')['name'].nunique()  # It's a perfect column

id
1001254     1
1002102     1
1002403     1
1002755     1
1003689     1
           ..
57365208    1
57365760    1
57366313    1
57366865    1
57367417    1
Name: name, Length: 102058, dtype: int64

### Check unique values in each columns

In [31]:
# column => host_identity_verified

df['host_identity_verified']
print(df['host_identity_verified'].value_counts())

# it's a perfect column

host_identity_verified
unconfirmed    51489
verified       51110
Name: count, dtype: int64

In [52]:
# column => host name
df['host_name'].value_counts()

host_name
michael         1287
david            764
john             581
alex             546
sonder (nyc)     516
                ...
ilayda             1
ngoc               1
yurika             1
ranjeet            1
adam + caro        1
Name: count, Length: 13158, dtype: int64

In [55]:
# column => neighbourhood_group
df['neighbourhood_group'].value_counts()

df['neighbourhood_group'] = df['neighbourhood_group'].replace(
    {
        'manhatan':'manhattan',
        'brookln':'brooklyn'
    }
)
df['neighbourhood_group'].value_counts()

neighbourhood_group
manhattan        43822
brooklyn         41843
queens           13267
bronx             2712
staten island      955
Name: count, dtype: int64

In [72]:
# column => neighbourhood
df['neighbourhood'].value_counts()

neighbourhood
bedford-stuyvesant        7953
williamsburg              7775
harlem                    5466
bushwick                  4982
hell's kitchen            3965
                          ...
rossville                    3
gerritsen beach              3
fort wadsworth               2
glen oaks                    2
chelsea, staten island       1
Name: count, Length: 224, dtype: int64

In [74]:
# country
df['country'].value_counts()

country
united states    102599
Name: count, dtype: int64

In [75]:
# cancellation_policy
df['cancellation_policy'].value_counts()

cancellation_policy
moderate    34419
strict      34106
flexible    34074
Name: count, dtype: int64

In [77]:
# room_type
df['room_type'].value_counts()

room_type
entire home/apt    53701
private room       46556
shared room         2226
hotel room           116
Name: count, dtype: int64

In [84]:
df

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,1001254,clean & quiet apt home by the park,80014485718,unconfirmed,madaline,brooklyn,kensington,40.64749,-73.97237,united states,False,strict,private room,2020.0,966,193,10.0,9.0
1,1002102,skylit midtown castle,52335172823,verified,jenna,manhattan,midtown,40.75362,-73.98377,united states,False,moderate,entire home/apt,2007.0,142,28,30.0,45.0
2,1002403,the village of harlem....new york !,78829239556,unconfirmed,elise,manhattan,harlem,40.80902,-73.94190,united states,True,flexible,private room,2005.0,620,124,3.0,0.0
3,1002755,home away from home,85098326012,unconfirmed,garry,brooklyn,clinton hill,40.68514,-73.95976,united states,True,moderate,entire home/apt,2005.0,368,74,30.0,270.0
4,1003689,entire apt: spacious studio/loft by central park,92037596077,verified,lyndon,manhattan,east harlem,40.79851,-73.94399,united states,False,moderate,entire home/apt,2009.0,204,41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,spare room in williamsburg,12312296767,verified,krik,brooklyn,williamsburg,40.70862,-73.94651,united states,False,flexible,private room,2003.0,844,169,1.0,0.0
102595,6092990,best location near columbia u,77864383453,unconfirmed,mifan,manhattan,morningside heights,40.80460,-73.96545,united states,True,moderate,private room,2016.0,837,167,1.0,1.0
102596,6093542,"comfy, bright room in brooklyn",69050334417,unconfirmed,megan,brooklyn,park slope,40.67505,-73.98045,united states,True,moderate,private room,2009.0,988,198,3.0,0.0
102597,6094094,big studio-one stop from midtown,11160591270,unconfirmed,christopher,queens,long island city,40.74989,-73.93777,united states,True,strict,entire home/apt,2015.0,546,109,2.0,5.0
102598,6094647,585 sf luxury studio,68170633372,unconfirmed,rebecca,manhattan,upper west side,40.76807,-73.98342,united states,False,flexible,entire home/apt,2010.0,1032,206,1.0,0.0

In [87]:
# cleaned dataset
# save that data
cleaned_df = df.to_csv(path_or_buf='Data/airbnb_cleaned_data.csv', index=False)
cleaned_df